name: Upload to Google Storage Dev Directory
on:
  push:
    branches_ignore:
      - master
  workflow_dispatch:
jobs:
  upload:
    name: Upload to Google Storage Dev Bucket 📤

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
      # actions/checkout MUST come before auth
      - name: Checkout Repo 🛒
        uses: 'actions/checkout@v3'

      - name: Authenticate to Google Cloud 🔓
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/940755218400/locations/global/workloadIdentityPools/github-actions/providers/github-actions'
          service_account: 'github-actions@stacked-327723.iam.gserviceaccount.com'

      - name: Upload to Google Cloud Dev Bucket 📤
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          path: 'javascript'
          destination: 'stacked_javascript/dev_javascript'
          parent: false
          headers: |-
            cache-control: no-store
