name: Minify JS and CSS files
on:
  pull_request_review:
    types: [submitted]
  workflow_dispatch:
jobs:
    minify_js:
      name: Minify Javascript 🚐
      runs-on: ubuntu-latest
      steps:
        # Check-out repository under $GITHUB_WORKSPACE, so auto-minify job can access it
        - uses: actions/checkout@v2

        - name: Minify /home
          uses: nizarmah/auto-minify@v2.1
          with:
            directory: 'javascript/home'
            output: 'mini_javascript/home'

        - name: Minify /add-firewood
          uses: nizarmah/auto-minify@v2.1
          with:
            directory: 'javascript/add-firewood'
            output: 'mini_javascript/add-firewood'

