name: Upload to Google Storage
on: [push]
jobs:
  job_id:

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
      # Check-out repository under $GITHUB_WORKSPACE, so auto-minify job can access it
      - uses: actions/checkout@v2

      - name: Auto Minify
        uses: nizarmah/auto-minify@v2.1
        with:
          directory: 'javascript'
          output: 'mini_javascript'

      # Auto commits minified files to the repository
      # Ignore it if you don't want to commit the files to the repository
      - name: Auto committing minified files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: 'mini_javascript'
          commit_message: "Github Action: Auto Minified JS and CSS files"
          branch: ${{ github.ref }}
